### ISSUE TITLE
failed to build Mozc.app

### ISSUE THREAD

**Issue by yodalee** [yodalee/mozc#105]
Ivans-MacBook-Pro:src ivan$ python build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput mac/mac.gyp:gen_launchd_confs
INFO: Running: ninja -C out_mac/Release GoogleJapaneseInput gen_launchd_confs
Traceback (most recent call last):
  File "build_mozc.py", line 1239, in <module>
    main()
  File "build_mozc.py", line 1226, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 857, in BuildMain
    BuildWithNinja(options, targets)
  File "build_mozc.py", line 831, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg] + ninja_targets)
  File "/Users/ivan/work/mozc/src/build_tools/util.py", line 92, in RunOrDie
    process = subprocess.Popen(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

when i am building the app for mac it shows likes these? how do i solve it? thanks

**Comment by yodalee** [comment]
This is the same problem I also get, but for unix/ibus/... targets.
